---
apiVersion: batch/v1
kind: Job
metadata:
  name: megacosm-dataloader
  labels:
    app: megacosm-dataloader
    tier: job
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: megacosm-dataloader
        tier: job
    spec:
      containers:
        - name: dataloader
          image: morgajel/megacosm-dataloader
          env:
          - name: REDISHOST
            value: "megacosm-redis.default.svc.cluster.local"
          - name: REDISPORT
            value: "6379"
      restartPolicy: Never
  backoffLimit: 5
