apiVersion: apps/v1
kind: Deployment
metadata:
  name: megacosm-webapp
spec:
  selector:
    matchLabels:
      app: megacosm-webapp
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: megacosm-webapp
        tier: frontend
    spec:
      containers:
        - name: megacosm-webapp
          image: morgajel/megacosm-webapp
          ports:
            - containerPort: 8000
              name: http
