---
apiVersion: batch/v1
kind: Job
metadata:
  name: megacosm-dataloader
  labels:
    app: megacosm-dataloader
    tier: job
spec:
  backoffLimit: 6 # number of retries before throwing error
  activeDeadlineSeconds: 10 # time to allow job to run
  template:
    metadata:
      labels:
        app: megacosm-dataloader
        tier: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          image: megacosm-dataloader:latest
          env:
          - name: REDISHOST
            valueFrom:
              resourceFieldRef:
                resource:  medadata.name
          - name: REDISPORT
            valueFrom:
              resourceFieldRef:
                resource: spec.ports.port


