apiVersion: apps/v1
kind: Deployment
metadata:
  name: megacosm-redis
  labels:
    app: redis
    tier: backend
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
        - name: megacosm-redis
          image: morgajel/megacosm-redis
          ports:
            - name: redis
              containerPort: 6379
