---
apiVersion: batch/v1
kind: Job
metadata:
  name: megacosm-dataloader
  labels:
    app: dataloader
    tier: job
spec:
  template:
    metadata:
      labels:
        app: dataloader
        tier: job
    spec:
      containers:
        - name: dataloader
          image: morgajel/megacosm-dataloader
          env:
          - name: REDISHOST
            value: "megacosm-redis.default.svc"
          - name: REDISPORT
            value: "6379"
      initContainers:
      - name: checkforredis
        image: busybox
        command: ['sh', '-c', 'until nslookup megacosm-redis.default.svc; do echo "waiting for backend" ; sleep 3; done; echo "backend is up"']
      restartPolicy: Never
  activeDeadlineSeconds: 600
  backoffLimit: 5
