---
apiVersion: v1
kind: Service
metadata:
  name: megacosm-redis
  labels:
    app: megacosm-redis
    tier: backend 
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: megacosm-redis
    tier: backend
